<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <IsTestProject>true</IsTestProject>
    <DefineConstants Condition="'$(StoreBuild)' == 'true'">$(DefineConstants);STORE_BUILD</DefineConstants>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/IPTray/IPTray.csproj" /></ItemGroup>
</Project>
